#!/bin/sh

# Include our script first, to reduce incompatibilities
export __DOTFILES_IS_TEST=true
CURR_DIR="$(dirname "$0")"
. "$CURR_DIR"/../bin/install.sh


# Tests start below
# --------------------------------------------------
describe "has_executable()"

it_will_find_an_existant_binary() {
  has="$(has_executable "sh" && echo "yes" || echo "no")"
  test "$has" "=" "yes"
}

it_will_not_find_a_fake_binary() {
  has="$(has_executable "totally-not-a-real-executable" && echo "yes" || echo "no")"
  test "$has" "=" "no"
}
