#!/bin/sh

# Include our script first, to reduce incompatibilities
export __DOTFILES_IS_TEST=true
CURR_DIR="$(dirname "$0")"
. "$CURR_DIR"/../bin/install.sh


# Tests start below
# --------------------------------------------------
describe "readlink()"

before() {
  _test_previousdir="$PWD"
  _test_workingdir="$(mktemp -d -t dotfiles.XXXXXX)"
  cd -P -- "$_test_workingdir"

  echo 'hello world' > foo
  ln -s foo bar
}

after() {
  cd -- "$_test_previousdir"
  rm -rf -- "$_test_workingdir"
}

it_will_read_a_link_target() {
  link_target="$(readlink_portable "bar")"
  test "$link_target" "=" "foo"
}

it_will_read_a_link_target_with_no_binary() {
  export __DOTFILES_TEST_NO_READLINK=true
  link_target="$(readlink_portable "bar")"

  test "$link_target" "=" "foo"
}
